"""
Local webhook signature verification.

The REFERENCE_VECTORS below were generated by the Go SDK, which canonicalises with the same
``encoding/json`` the QBitFlow API itself uses. Asserting against them keeps all four SDKs
byte-identical: if this SDK's canonical form or signature ever drifts from Go's, these fail
rather than silently rejecting genuine webhooks in production.
"""

import time

import pytest

from qbitflow.exceptions.exceptions import ValidationError
from qbitflow.webhooks import (
    TEST_WEBHOOK_ID,
    canonical_json,
    compute_webhook_signature,
    extract_webhook_headers,
    verify_webhook_signature,
)

SECRET = "whsec_test_0123456789abcdef"
TIMESTAMP = "1700000000"

# (name, input, expected canonical form, expected signature)
REFERENCE_VECTORS = [
    (
        "arrayOrder",
        '{"items":[3,1,2]}',
        '{"items":[3,1,2]}',
        "sha256=8270d9e92c09c45b1ef5b4ec50e32e2b1c3fea8a7f49947d6af0fee131854d27",
    ),
    (
        "emptyObj",
        "{}",
        "{}",
        "sha256=86e42664e55bdef9d21c29ec99ef840bb60f05f718392629bb0eb162a585147e",
    ),
    (
        "html",
        '{"url":"https://x.test/a?b=1&c=2","tag":"<b>"}',
        '{"tag":"\\u003cb\\u003e","url":"https://x.test/a?b=1\\u0026c=2"}',
        "sha256=28b274c01275f3ea7c03f3feb7fd2ec52a9594333779cae66f975d8914bc9383",
    ),
    (
        "nested",
        '{"z":{"y":1,"x":2},"a":[{"d":4,"c":3}]}',
        '{"a":[{"c":3,"d":4}],"z":{"x":2,"y":1}}',
        "sha256=710b9fed39bfd9f5c087f26f4bbb91eb5a30a56fc8e2f8e4ba41c0b92b7949a7",
    ),
    (
        "nulls",
        '{"a":null,"b":false,"c":true}',
        '{"a":null,"b":false,"c":true}',
        "sha256=2cdc9b14b681f7f80c7f4308cfe4a080840c16db5e2a2fca46e8d2a9e99677b8",
    ),
    (
        "numbers",
        '{"int":2592000,"float":9.99,"zero":0,"neg":-1.5}',
        '{"float":9.99,"int":2592000,"neg":-1.5,"zero":0}',
        "sha256=d7939b32907de3fdfb5db88092caf53aa58234e3ec62ca9813d24df4bab78d3e",
    ),
    (
        "realWebhook",
        '{"uuid":"pay@01a0c0c7","txType":"payment","status":{"status":"completed","txHash":"0xabc"},"managementPageLink":"https://qbitflow.app/m?id=1&k=2"}',
        '{"managementPageLink":"https://qbitflow.app/m?id=1\\u0026k=2","status":{"status":"completed","txHash":"0xabc"},"txType":"payment","uuid":"pay@01a0c0c7"}',
        "sha256=bdce3332c824b8abbe798034e6f8156d914c81c088aad6f5694df3b98241c540",
    ),
    (
        "simple",
        '{"a":1,"b":2}',
        '{"a":1,"b":2}',
        "sha256=7293f8a9be38cc10138c04b2ca50bb65533bf356f476552981079eebf7b3a53a",
    ),
    (
        "unicode",
        '{"name":"Caf\u00e9 Cr\u00e8me \u65e5\u672c\u8a9e"}',
        '{"name":"Caf\u00e9 Cr\u00e8me \u65e5\u672c\u8a9e"}',
        "sha256=8828459bb4f050a0ae4d633d71edefa6027c1cc39933e8b27de9bc5fafd491ac",
    ),
    (
        "unsorted",
        '{"b":2,"a":1,"c":3}',
        '{"a":1,"b":2,"c":3}',
        "sha256=cefa417c919e24dadad16670fb997f379aece68be25f46d70bd2ee6541bb7b0a",
    ),
    (
        "wholeFloats",
        '{"whole":1.0,"negWhole":-2.0,"frac":2.50}',
        '{"frac":2.5,"negWhole":-2,"whole":1}',
        "sha256=568f803efa06262d9bc43020a326a2d335739bc54c2f1f546d2f0c4d7ac70619",
    ),
]


def now_ts() -> str:
    return str(int(time.time()))


class TestReferenceVectors:
    """Cross-SDK byte-for-byte agreement with the Go implementation."""

    @pytest.mark.parametrize("name,payload,canonical,_sig", REFERENCE_VECTORS)
    def test_canonical_form_matches_go(self, name, payload, canonical, _sig):
        assert canonical_json(payload) == canonical, f"canonical form drifted for {name}"

    @pytest.mark.parametrize("name,payload,_canonical,signature", REFERENCE_VECTORS)
    def test_signature_matches_go(self, name, payload, _canonical, signature):
        assert (
            compute_webhook_signature(SECRET, TIMESTAMP, payload) == signature
        ), f"signature drifted for {name}"


class TestCanonicalJson:
    def test_sorts_keys_at_every_level(self):
        assert canonical_json('{"b":2,"a":1}') == '{"a":1,"b":2}'
        assert canonical_json('{"z":{"y":1,"x":2}}') == '{"z":{"x":2,"y":1}}'

    def test_preserves_array_order(self):
        # Arrays are ordered by definition: sorting them would change meaning.
        assert canonical_json('{"items":[3,1,2]}') == '{"items":[3,1,2]}'

    def test_drops_insignificant_whitespace(self):
        assert canonical_json('{\n  "a" : 1 }') == '{"a":1}'

    def test_accepts_bytes_str_and_decoded_objects(self):
        expected = '{"a":1,"b":2}'
        assert canonical_json('{"b":2,"a":1}') == expected
        assert canonical_json(b'{"b":2,"a":1}') == expected
        assert canonical_json({"b": 2, "a": 1}) == expected

    def test_whole_floats_render_as_integers_like_go(self):
        # Go decodes JSON numbers to float64 and re-encodes 1.0 as "1"; Python would keep
        # "1.0" and produce a different signature for an identical payload.
        assert canonical_json('{"a":1.0}') == '{"a":1}'
        assert canonical_json({"a": 1.0}) == '{"a":1}'

    def test_booleans_are_not_coerced_to_numbers(self):
        # bool is a subclass of int in Python: True must stay true, not become 1.
        assert canonical_json('{"a":true,"b":false}') == '{"a":true,"b":false}'

    def test_rejects_invalid_json_and_missing_payloads(self):
        with pytest.raises(ValidationError):
            canonical_json("{not json")
        with pytest.raises(ValidationError):
            canonical_json(None)


class TestVerifyWebhookSignature:
    payload = '{"uuid":"pay@abc","txType":"payment"}'

    def test_accepts_a_genuine_webhook(self):
        ts = now_ts()
        sig = compute_webhook_signature(SECRET, ts, self.payload)
        verify_webhook_signature(SECRET, ts, sig, self.payload)

    def test_accepts_a_payload_whose_keys_were_reordered(self):
        ts = now_ts()
        sig = compute_webhook_signature(SECRET, ts, '{"a":1,"b":2}')
        verify_webhook_signature(SECRET, ts, sig, '{"b":2,"a":1}')

    def test_rejects_a_tampered_payload(self):
        ts = now_ts()
        sig = compute_webhook_signature(SECRET, ts, self.payload)
        with pytest.raises(ValidationError, match="mismatch"):
            verify_webhook_signature(SECRET, ts, sig, '{"uuid":"pay@EVIL"}')

    def test_rejects_a_tampered_timestamp(self):
        ts = now_ts()
        sig = compute_webhook_signature(SECRET, ts, self.payload)
        with pytest.raises(ValidationError, match="mismatch"):
            verify_webhook_signature(SECRET, str(int(ts) - 30), sig, self.payload)

    def test_rejects_the_wrong_secret(self):
        ts = now_ts()
        sig = compute_webhook_signature(SECRET, ts, self.payload)
        with pytest.raises(ValidationError, match="mismatch"):
            verify_webhook_signature("whsec_wrong", ts, sig, self.payload)

    def test_rejects_a_replayed_webhook(self):
        old = str(int(time.time()) - 600)
        sig = compute_webhook_signature(SECRET, old, self.payload)
        with pytest.raises(ValidationError, match="expired"):
            verify_webhook_signature(SECRET, old, sig, self.payload)

    def test_rejects_a_future_timestamp(self):
        # Guards against a forged future timestamp extending the replay window.
        future = str(int(time.time()) + 600)
        sig = compute_webhook_signature(SECRET, future, self.payload)
        with pytest.raises(ValidationError, match="expired"):
            verify_webhook_signature(SECRET, future, sig, self.payload)

    def test_honours_a_custom_replay_window(self):
        old = str(int(time.time()) - 600)
        sig = compute_webhook_signature(SECRET, old, self.payload)
        verify_webhook_signature(SECRET, old, sig, self.payload, max_timestamp_age_seconds=1800)

    def test_rejects_a_non_numeric_timestamp(self):
        with pytest.raises(ValidationError):
            verify_webhook_signature(SECRET, "nope", "sha256=abc", self.payload)

    @pytest.mark.parametrize("bad", ["", "sha256=", "deadbeef", "sha512=abc"])
    def test_rejects_malformed_signatures(self, bad):
        with pytest.raises(ValidationError):
            verify_webhook_signature(SECRET, now_ts(), bad, self.payload)


class TestExtractWebhookHeaders:
    def test_reads_headers_case_insensitively(self):
        h = extract_webhook_headers(
            {
                "x-webhook-signature-256": "sha256=abc",
                "X-Webhook-Timestamp": "1700000000",
                "x-webhook-id": "pay@abc",
            }
        )
        assert h["signature"] == "sha256=abc"
        assert h["timestamp"] == "1700000000"
        assert h["webhook_id"] == "pay@abc"
        assert h["is_test"] is False

    def test_flags_the_dashboard_test_webhook(self):
        h = extract_webhook_headers({"X-Webhook-Id": TEST_WEBHOOK_ID})
        assert h["is_test"] is True

    def test_takes_the_first_value_of_a_repeated_header(self):
        h = extract_webhook_headers({"x-webhook-timestamp": ["1700000000", "1700000001"]})
        assert h["timestamp"] == "1700000000"

    def test_missing_headers_yield_empty_strings(self):
        h = extract_webhook_headers({})
        assert h["signature"] == ""
        assert h["timestamp"] == ""
        assert h["is_test"] is False


class TestWebSocketUrl:
    """The SDK builds the status WebSocket URL but does not open the socket."""

    def test_derives_a_ws_scheme_from_the_base_url(self, client):
        from qbitflow.dto.transaction.status import TransactionType

        url = client.transaction_status.get_websocket_url(
            "pay@abc", TransactionType.ONE_TIME_PAYMENT
        )

        assert url.startswith("ws://") or url.startswith("wss://")
        assert "/transaction/status/ws" in url
        assert "txUUID=pay@abc" in url
        assert "txType=payment" in url

    def test_rejects_an_empty_uuid(self, client):
        from qbitflow.dto.transaction.status import TransactionType

        with pytest.raises(ValidationError):
            client.transaction_status.get_websocket_url("", TransactionType.ONE_TIME_PAYMENT)


class TestOptionalFieldsEmptyString:
    """An empty optional field means "not provided", matching the API's omitempty."""

    def test_empty_strings_are_treated_as_absent(self):
        from qbitflow.dto.transaction.session import CreatePaymentSessionDto

        # Must not raise: os.environ.get("SUCCESS_URL", "") is a normal pattern.
        CreatePaymentSessionDto(product_id=339, success_url="", product_name="", description="")

    def test_a_non_empty_bad_value_is_still_rejected(self):
        import pydantic

        from qbitflow.dto.transaction.session import CreatePaymentSessionDto

        with pytest.raises(pydantic.ValidationError):
            CreatePaymentSessionDto(product_id=339, success_url="javascript:alert(1)")
