"""The shared cross-SDK conformance vectors (generated by running the Go reference SDK):
signature, events, validation, decoding and requests. Every ``expect`` must be reproduced."""

from __future__ import annotations

import base64
import inspect
import json
import math
import re
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import parse_qsl, unquote

import httpx
import pytest

from qbitflow import (
    NOT_GIVEN,
    Duration,
    QBitFlow,
    RequestOptions,
    ServerError,
    SubscriptionSessionData,
    SubscriptionTermsParams,
    UnknownEvent,
    ValidationError,
    WebhookSignatureError,
    webhooks,
)
from qbitflow.models import Model
from qbitflow.models._base import ZERO_TIME, parse_time
from qbitflow.models.events import EventDetail

from .conftest import FIXTURES

VECTORS = FIXTURES / "vectors"
API_KEY = "sk_test_conformance"


def load(name: str) -> List[Dict[str, Any]]:
    return json.loads((VECTORS / f"{name}.json").read_text())["cases"]


def ids(cases: List[Dict[str, Any]]) -> List[str]:
    return [c["name"] for c in cases]


# ── Invoking a method from a vector ──────────────────────────────────────────

_SNAKE = re.compile(r"(?<!^)(?=[A-Z])")
_NON_FINITE = {"NaN": math.nan, "Infinity": math.inf, "-Infinity": -math.inf}


def snake(name: str) -> str:
    return _SNAKE.sub("_", name).lower()


def _duration(value: Any) -> Any:
    if isinstance(value, dict):
        return Duration(value=value.get("value", 0), unit=value.get("unit"))
    return value


def convert_param(key: str, value: Any) -> Any:
    if key in ("price", "refundPercent", "organizationFeePercent") and value in _NON_FINITE:
        return _NON_FINITE[value]
    if key in ("frequency", "trialPeriod"):
        return _duration(value)
    if key == "subscription" and isinstance(value, dict):
        return SubscriptionTermsParams(
            frequency=_duration(value.get("frequency")),
            trial_period=_duration(value.get("trialPeriod")),
            min_periods=value.get("minPeriods"),
        )
    if key in ("createdAfter", "createdBefore") and isinstance(value, str):
        return parse_time(value)
    return value


_PATH_NAMES = {"from_date": "from", "to_date": "to"}


def resolve(client: QBitFlow, method: str) -> Any:
    target: Any = client
    for part in method.split("."):
        target = getattr(target, snake(part))
    return target


def invoke(client: QBitFlow, case: Dict[str, Any]) -> Any:
    """Call ``case["method"]`` with ``case["args"]`` and ``case.get("options")``."""
    args = case.get("args", {})
    if case.get("client") is not None:
        client = client.on_behalf_of(case["client"]["onBehalfOf"])
    fn = resolve(client, case["method"])
    sig = inspect.signature(fn)
    positional = []
    kwargs: Dict[str, Any] = {}
    for name, param in sig.parameters.items():
        if param.kind is inspect.Parameter.POSITIONAL_OR_KEYWORD:
            spec = _PATH_NAMES.get(name) or re.sub(r"_([a-z])", lambda m: m.group(1).upper(), name)
            raw = args.get(spec)
            if spec == "rawBody" and "rawBodyBase64" in args:
                raw = base64.b64decode(args["rawBodyBase64"])
            positional.append(raw)
    for key, value in args.get("params", {}).items():
        kwargs[snake(key)] = convert_param(key, value)
    # A required keyword argument the vector leaves out is passed as None: the SDK must refuse it
    # with a ValidationError naming the field, like the other SDKs.
    for name, param in sig.parameters.items():
        if (
            param.kind is inspect.Parameter.KEYWORD_ONLY
            and param.default is inspect.Parameter.empty
            and name not in kwargs
        ):
            kwargs[name] = None
    if "options" in case:
        opts = case["options"]
        kwargs["options"] = RequestOptions(
            on_behalf_of=opts.get("onBehalfOf"),
            idempotency_key=opts.get("idempotencyKey"),
            request_id=opts.get("requestId"),
        )
    result = fn(*positional, **kwargs)
    if inspect.isgenerator(result):  # pragma: no cover - vectors call list methods
        result = list(result)
    return result


def conformance_client(handler: Any) -> Tuple[QBitFlow, List[httpx.Request]]:
    seen: List[httpx.Request] = []

    def record(request: httpx.Request) -> httpx.Response:
        request.read()
        seen.append(request)
        return handler(request)

    http = httpx.Client(transport=httpx.MockTransport(record))
    client = QBitFlow(
        API_KEY, base_url="https://conformance.test/v2", http_client=http, max_retries=0
    )
    return client, seen


# ── signature.json ───────────────────────────────────────────────────────────


@pytest.mark.parametrize("case", load("signature"), ids=ids(load("signature")))
def test_signature_vectors(case: Dict[str, Any]) -> None:
    raw = base64.b64decode(case["rawBodyBase64"]) if "rawBodyBase64" in case else case["rawBody"]
    try:
        webhooks.verify(
            raw, case["header"], case["secret"], tolerance=case["tolerance"], now=case["now"]
        )
        got = "ok"
    except WebhookSignatureError as exc:
        got = str(exc.reason)
    except ValidationError:
        got = "validationError"
    assert got == case["expect"], case.get("note", "")


# ── Probes ───────────────────────────────────────────────────────────────────

_INDEX = re.compile(r"([^\[\]]*)((?:\[\d+\])*)")


def _field(value: Any, key: str) -> Tuple[bool, Any]:
    if isinstance(value, dict):
        return (key in value), value.get(key)
    if isinstance(value, EventDetail) and key not in ("deliveries",):
        value = value.event
    if isinstance(value, Model):
        for name, info in type(value).model_fields.items():
            if info.alias == key or name == key:
                return True, getattr(value, name)
        return False, None
    raise AssertionError(f"cannot read {key!r} on {type(value).__name__}")


def read(value: Any, path: str) -> Tuple[bool, Any]:
    """Read a wire-named path (``items[0].metadata.txAmounts.usd.merchant``) on a result."""
    if path == "":
        return True, value
    found = True
    for segment in path.split("."):
        match = _INDEX.fullmatch(segment)
        assert match is not None, segment
        key, indexes = match.groups()
        if key:
            found, value = _field(value, key)
            if not found or value is None:
                return found, None
        for index in re.findall(r"\d+", indexes):
            value = value[int(index)]
    return found, value


def plain(value: Any) -> Any:
    """A decoded value as JSON-like data (models dumped by alias, enums as strings)."""
    if isinstance(value, Model):
        return value.model_dump(mode="json", by_alias=True, exclude_none=True)
    if isinstance(value, list):
        return [plain(v) for v in value]
    if isinstance(value, dict):
        return {k: plain(v) for k, v in value.items()}
    if isinstance(value, str):
        return str(value)
    return value


def same_json(got: Any, want: Any) -> bool:
    if isinstance(want, dict) and isinstance(got, dict):
        # The SDK leaves None fields out: compare the expected keys, ignoring expected nulls.
        return all(
            same_json(got.get(k), v) if v is not None else got.get(k) in (None, "", [])
            for k, v in want.items()
        )
    if isinstance(want, list) and isinstance(got, list):
        return len(got) == len(want) and all(same_json(g, w) for g, w in zip(got, want))
    if isinstance(want, (int, float)) and not isinstance(want, bool):
        return isinstance(got, (int, float)) and not isinstance(got, bool) and got == want
    return bool(got == want)


def check_probe(result: Any, probe: Dict[str, Any]) -> None:
    found, got = read(result, probe["path"])
    want = probe["value"]
    where = f"probe {probe['path']}: got {got!r}, want {want!r}"
    if probe.get("kind") == "time":
        if want is None:
            assert got is None or got == ZERO_TIME, where
        else:
            assert isinstance(got, datetime) and got == parse_time(want), where
        return
    if probe.get("optional") and want in ("", None):
        assert got in ("", None), where
        return
    if want is None:
        assert got is None, where
        return
    assert same_json(plain(got), want), where


# ── events.json ──────────────────────────────────────────────────────────────


@pytest.mark.parametrize("case", load("events"), ids=ids(load("events")))
def test_event_vectors(case: Dict[str, Any]) -> None:
    expect = case["expect"]
    if not expect["ok"]:
        with pytest.raises(ValidationError):
            webhooks.parse_event(case["rawBody"])
        return
    event = webhooks.parse_event(case["rawBody"])
    assert event.id == expect["id"]
    assert event.type == expect["type"]
    assert event.test == expect["test"]
    assert (event.user_uuid or "") == expect["userUuid"]
    assert (not isinstance(event, UnknownEvent)) == expect["known"]
    if "dataShape" in expect:
        shape = "subscription" if isinstance(event.data, SubscriptionSessionData) else "payment"
        assert shape == expect["dataShape"]
    for probe in case.get("probes", []):
        check_probe(event, probe)


# ── validation.json ──────────────────────────────────────────────────────────


@pytest.mark.parametrize("case", load("validation"), ids=ids(load("validation")))
def test_validation_vectors(case: Dict[str, Any]) -> None:
    client, seen = conformance_client(lambda _r: httpx.Response(200, json={}))
    expect = case["expect"]
    try:
        invoke(client, case)
    except ValidationError as exc:
        if seen:  # the request was sent: a response decoding issue is irrelevant here
            assert exc.status is not None
        else:
            assert expect != "ok", f"refused locally: {exc}"
            assert exc.status is None and exc.code == ""
            assert {f.field for f in exc.field_errors} == set(expect["fields"]), str(exc)
            return
    except WebhookSignatureError as exc:
        assert not seen
        assert expect == {"errorClass": "WebhookSignatureError", "reason": str(exc.reason)}
        return
    except ServerError:
        assert seen  # a decoding failure after the request was sent
    assert expect == "ok", f"expected a local refusal {expect}, the request was sent"
    assert len(seen) == 1


# ── decoding.json ────────────────────────────────────────────────────────────


@pytest.mark.parametrize("case", load("decoding"), ids=ids(load("decoding")))
def test_decoding_vectors(case: Dict[str, Any]) -> None:
    client, _ = conformance_client(
        lambda _r: httpx.Response(
            case["status"],
            content=case["body"].encode("utf-8"),
            headers={"Content-Type": "application/json"},
        )
    )
    if case["expect"] == "serverError":
        with pytest.raises(ServerError):
            invoke(client, case)
        return
    result = invoke(client, case)
    for probe in case.get("probes", []):
        check_probe(result, probe)


# ── requests.json ────────────────────────────────────────────────────────────

_UUID_V4 = re.compile(r"[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}")


@pytest.mark.parametrize("case", load("requests"), ids=ids(load("requests")))
def test_request_vectors(case: Dict[str, Any]) -> None:
    client, seen = conformance_client(lambda _r: httpx.Response(200, json={}))
    try:
        invoke(client, case)
    except ServerError:
        pass  # the stub's {} may not fit the method's answer: only the request matters
    assert len(seen) == 1
    req, want = seen[0], case["request"]
    assert req.method == want["verb"]

    raw_path, _, raw_query = req.url.raw_path.decode("ascii").partition("?")
    assert raw_path.startswith("/v2/") or raw_path == "/v2"
    raw_segments = raw_path[len("/v2/") :].split("/")
    assert all(s not in (".", "..") for s in raw_segments)
    assert [unquote(s) for s in raw_segments] == want["pathSegments"]

    assert "+" not in raw_query
    got_query = sorted(parse_qsl(raw_query, keep_blank_values=True))
    want_query = sorted((k, v) for k, v in want["query"])
    assert [k for k, _ in got_query] == [k for k, _ in want_query]
    for (key, got_value), (_, want_value) in zip(got_query, want_query):
        if key in ("createdAfter", "createdBefore"):
            assert parse_time(got_value) == parse_time(want_value)
        else:
            assert got_value == want_value, key

    for name, value in want["headers"].items():
        got_header: Optional[str] = req.headers.get(name)
        if value is None:
            assert got_header is None, name
        elif value == "<uuid-v4>":
            assert got_header is not None and _UUID_V4.fullmatch(got_header), name
        else:
            assert got_header == value, name

    body = req.content
    if want["body"] is None:
        assert body == b""
    else:
        assert same_body(json.loads(body), want["body"])


def same_body(got: Any, want: Any) -> bool:
    if isinstance(want, dict):
        return (
            isinstance(got, dict)
            and set(got) == set(want)
            and all(same_body(got[k], want[k]) for k in want)
        )
    if isinstance(want, list):
        return (
            isinstance(got, list)
            and len(got) == len(want)
            and all(same_body(g, w) for g, w in zip(got, want))
        )
    if isinstance(want, bool) or isinstance(got, bool):
        return got is want
    return bool(got == want)


def test_not_given_is_falsy() -> None:
    assert not NOT_GIVEN and repr(NOT_GIVEN) == "NOT_GIVEN"
