"""
Local webhook signature verification.

The REFERENCE_VECTORS below were generated by the Go SDK, which canonicalises with the same
``encoding/json`` the QBitFlow API itself uses. Asserting against them keeps all four SDKs
byte-identical: if this SDK's canonical form or signature ever drifts from Go's, these fail
rather than silently rejecting genuine webhooks in production.
"""

import json
import time

import pytest

from qbitflow.dto.transaction.session import (
    OneTimePaymentSession,
    SessionWebhookResponse,
    SubscriptionSession,
)
from qbitflow.dto.transaction.subscription import (
    SubscriptionHistory,
    SubscriptionStatus,
    SubscriptionWebhookType,
)
from qbitflow.exceptions.exceptions import ValidationError
from qbitflow.webhooks import (
    TEST_WEBHOOK_ID,
    canonical_json,
    compute_webhook_signature,
    extract_webhook_headers,
    parse_session_webhook,
    parse_subscription_webhook,
    verify_webhook_signature,
)

SECRET = "whsec_test_0123456789abcdef"
TIMESTAMP = "1700000000"

# (name, input, expected canonical form, expected signature)
REFERENCE_VECTORS = [
    (
        "arrayOrder",
        '{"items":[3,1,2]}',
        '{"items":[3,1,2]}',
        "sha256=8270d9e92c09c45b1ef5b4ec50e32e2b1c3fea8a7f49947d6af0fee131854d27",
    ),
    (
        "emptyObj",
        "{}",
        "{}",
        "sha256=86e42664e55bdef9d21c29ec99ef840bb60f05f718392629bb0eb162a585147e",
    ),
    (
        "html",
        '{"url":"https://x.test/a?b=1&c=2","tag":"<b>"}',
        '{"tag":"\\u003cb\\u003e","url":"https://x.test/a?b=1\\u0026c=2"}',
        "sha256=28b274c01275f3ea7c03f3feb7fd2ec52a9594333779cae66f975d8914bc9383",
    ),
    (
        "nested",
        '{"z":{"y":1,"x":2},"a":[{"d":4,"c":3}]}',
        '{"a":[{"c":3,"d":4}],"z":{"x":2,"y":1}}',
        "sha256=710b9fed39bfd9f5c087f26f4bbb91eb5a30a56fc8e2f8e4ba41c0b92b7949a7",
    ),
    (
        "nulls",
        '{"a":null,"b":false,"c":true}',
        '{"a":null,"b":false,"c":true}',
        "sha256=2cdc9b14b681f7f80c7f4308cfe4a080840c16db5e2a2fca46e8d2a9e99677b8",
    ),
    (
        "numbers",
        '{"int":2592000,"float":9.99,"zero":0,"neg":-1.5}',
        '{"float":9.99,"int":2592000,"neg":-1.5,"zero":0}',
        "sha256=d7939b32907de3fdfb5db88092caf53aa58234e3ec62ca9813d24df4bab78d3e",
    ),
    (
        "realWebhook",
        (
            '{"uuid":"pay@01a0c0c7","txType":"payment",'
            '"status":{"status":"completed","txHash":"0xabc"},'
            '"managementPageLink":"https://qbitflow.app/m?id=1&k=2"}'
        ),
        (
            '{"managementPageLink":"https://qbitflow.app/m?id=1\\u0026k=2",'
            '"status":{"status":"completed","txHash":"0xabc"},"txType":"payment",'
            '"uuid":"pay@01a0c0c7"}'
        ),
        "sha256=bdce3332c824b8abbe798034e6f8156d914c81c088aad6f5694df3b98241c540",
    ),
    (
        "simple",
        '{"a":1,"b":2}',
        '{"a":1,"b":2}',
        "sha256=7293f8a9be38cc10138c04b2ca50bb65533bf356f476552981079eebf7b3a53a",
    ),
    (
        "unicode",
        '{"name":"Caf\u00e9 Cr\u00e8me \u65e5\u672c\u8a9e"}',
        '{"name":"Caf\u00e9 Cr\u00e8me \u65e5\u672c\u8a9e"}',
        "sha256=8828459bb4f050a0ae4d633d71edefa6027c1cc39933e8b27de9bc5fafd491ac",
    ),
    (
        "unsorted",
        '{"b":2,"a":1,"c":3}',
        '{"a":1,"b":2,"c":3}',
        "sha256=cefa417c919e24dadad16670fb997f379aece68be25f46d70bd2ee6541bb7b0a",
    ),
    (
        "wholeFloats",
        '{"whole":1.0,"negWhole":-2.0,"frac":2.50}',
        '{"frac":2.5,"negWhole":-2,"whole":1}',
        "sha256=568f803efa06262d9bc43020a326a2d335739bc54c2f1f546d2f0c4d7ac70619",
    ),
]


# Golden vectors generated by the Go SDK (the API's own encoding/json) — shared by all
# four SDKs. Fields: name, payload, secret, timestamp, canonical, signature.
GOLDEN_VECTORS = [
    {
        "name": "empty_object",
        "payload": "{}",
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": "{}",
        "signature": "sha256=122d17b8a94e9170db2d91edb1a4060a1847a8de8020e3a1a20ea84293f28d22",
    },
    {
        "name": "key_order_and_types",
        "payload": (
            '{"zeta":1,"alpha":"a","Beta":true,"nested":{"y":null,"x":[1,2,{"b":"B","a":"A"'
            '}]},"émoji":"☕"}'
        ),
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": (
            '{"Beta":true,"alpha":"a","nested":{"x":[1,2,{"a":"A","b":"B"}],"y":null},"zeta'
            '":1,"émoji":"☕"}'
        ),
        "signature": "sha256=078c8862e2a4b67245ff3c04405d313c1815d19e3f246446583919260df7332d",
    },
    {
        "name": "html_and_unicode_escaping",
        "payload": (
            '{"msg":"<b>ok</b> & done / fine \\"q\\" \\\\ back","line":"a\u2028b\u2029c\\tt'
            'ab\\nnl","dq":"<script>"}'
        ),
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": (
            '{"dq":"\\u003cscript\\u003e","line":"a\\u2028b\\u2029c\\ttab\\nnl","msg":"\\u0'
            '03cb\\u003eok\\u003c/b\\u003e \\u0026 done / fine \\"q\\" \\\\ back"}'
        ),
        "signature": "sha256=220a10812e56a3cd202440cdbe7fa255515979760c4d15f821b3a6fea34564a4",
    },
    {
        "name": "numbers_float64_semantics",
        "payload": (
            '{"n":[1e-7,1e-6,0.00001234,0.0001234,0.001,1e15,1e16,1e20,1e21,1.5e22,12345678'
            "9.123,0.1,100.0,10.5,0,5e-324,1.7976931348623157e308,9007199254740993,2.5e-5,1"
            "234567890123456789,19.99,-5]}"
        ),
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": (
            '{"n":[1e-7,0.000001,0.00001234,0.0001234,0.001,1000000000000000,10000000000000'
            "000,100000000000000000000,1e+21,1.5e+22,123456789.123,0.1,100,10.5,0,5e-324,1."
            "7976931348623157e+308,9007199254740992,0.000025,1234567890123456800,19.99,-5]}"
        ),
        "signature": "sha256=2969a1f1c606f2cefbc8dadef939ccf2337d0388827819c888137454deec56b8",
    },
    {
        "name": "empty_containers",
        "payload": '{"emptyObj":{},"emptyArr":[],"list":[{},[],[[]],[{}]],"s":""}',
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": '{"emptyArr":[],"emptyObj":{},"list":[{},[],[[]],[{}]],"s":""}',
        "signature": "sha256=de1584470053d814ee8903db86fbe07517e13a0282c1e682587ed77659f9231a",
    },
    {
        "name": "transaction_webhook",
        "payload": (
            '{"uuid":"pay@01997c89-d0e9-7c9a-9886-fe7709919695","txType":"payment","status"'
            ':{"status":"completed","txHash":"0x9f2c","settlementDetails":{"feeBps":100,"tx'
            'Metadata":{"networkFees":{"amount":"21000","unitsConsumed":21000},"blockData":'
            '{"number":"1234567","timestamp":1758539990},"mainCurrencyPriceUSD":0.00001234}'
            ',"txAmounts":{"usd":{"platform":0.2,"merchant":19.79},"minUnits":{"platform":"'
            '200000","organization":"0","referral":"0","merchant":"19790000"}}}},"session":'
            '{"uuid":"pay@01997c89-d0e9-7c9a-9886-fe7709919695","reference":"ORD/2026/17","'
            'productId":42,"productName":"Café Premium","description":"Best <coffee> & tea"'
            ',"price":19.99,"successUrl":"https://shop.example.com/ok?o=17&x=1","organizati'
            'onId":7,"organizationName":"Acme","feeBps":100,"userId":0,"test":false,"custom'
            'erUUID":"3f2b1c1e-8d1a-4c2b-9b0e-1a2b3c4d5e6f","txType":"payment","availableCu'
            'rrencies":[1,2,3]},"managementPageLink":"https://app.qbitflow.app/m/abc"}'
        ),
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": (
            '{"managementPageLink":"https://app.qbitflow.app/m/abc","session":{"availableCu'
            'rrencies":[1,2,3],"customerUUID":"3f2b1c1e-8d1a-4c2b-9b0e-1a2b3c4d5e6f","descr'
            'iption":"Best \\u003ccoffee\\u003e \\u0026 tea","feeBps":100,"organizationId":'
            '7,"organizationName":"Acme","price":19.99,"productId":42,"productName":"Café P'
            'remium","reference":"ORD/2026/17","successUrl":"https://shop.example.com/ok?o='
            '17\\u0026x=1","test":false,"txType":"payment","userId":0,"uuid":"pay@01997c89-'
            'd0e9-7c9a-9886-fe7709919695"},"status":{"settlementDetails":{"feeBps":100,"txA'
            'mounts":{"minUnits":{"merchant":"19790000","organization":"0","platform":"2000'
            '00","referral":"0"},"usd":{"merchant":19.79,"platform":0.2}},"txMetadata":{"bl'
            'ockData":{"number":"1234567","timestamp":1758539990},"mainCurrencyPriceUSD":0.'
            '00001234,"networkFees":{"amount":"21000","unitsConsumed":21000}}},"status":"co'
            'mpleted","txHash":"0x9f2c"},"txType":"payment","uuid":"pay@01997c89-d0e9-7c9a-'
            '9886-fe7709919695"}'
        ),
        "signature": "sha256=c6e845486a0c5d2b9f3d1fca4a9c4190649ed46b06db74d71bd2703358a411ec",
    },
    {
        "name": "subscription_billing_webhook",
        "payload": (
            '{"subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","subscriptionRe'
            'ference":"plan-pro","type":"billing","data":{"uuid":"sub-hist@01a0c5be-0000-70'
            '00-8000-000000000002","createdAt":"2026-09-21T22:02:09.986381+02:00","from":"0'
            'xfrom","to":"0xto","amount":9.99,"amountMinUnits":"9990000","currencyId":2,"te'
            'st":true,"transactionHash":"0xhash","organizationId":7,"userId":3,"name":"Pro"'
            ',"description":"Monthly","productId":9,"subscriptionUUID":"sub@01a0c5be-0000-7'
            '000-8000-000000000001","metadata":{"feeBps":100,"txMetadata":{"networkFees":{"'
            'amount":"0","unitsConsumed":0},"blockData":{"number":"","timestamp":0}},"txAmo'
            'unts":{"usd":{"platform":0.0999,"merchant":9.8901},"minUnits":{"platform":"999'
            '00","organization":"0","referral":"0","merchant":"9890100"}}}}}'
        ),
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": (
            '{"data":{"amount":9.99,"amountMinUnits":"9990000","createdAt":"2026-09-21T22:0'
            '2:09.986381+02:00","currencyId":2,"description":"Monthly","from":"0xfrom","met'
            'adata":{"feeBps":100,"txAmounts":{"minUnits":{"merchant":"9890100","organizati'
            'on":"0","platform":"99900","referral":"0"},"usd":{"merchant":9.8901,"platform"'
            ':0.0999}},"txMetadata":{"blockData":{"number":"","timestamp":0},"networkFees":'
            '{"amount":"0","unitsConsumed":0}}},"name":"Pro","organizationId":7,"productId"'
            ':9,"subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000000001","test":true,"'
            'to":"0xto","transactionHash":"0xhash","userId":3,"uuid":"sub-hist@01a0c5be-000'
            '0-7000-8000-000000000002"},"subscriptionReference":"plan-pro","subscriptionUUI'
            'D":"sub@01a0c5be-0000-7000-8000-000000000001","type":"billing"}'
        ),
        "signature": "sha256=c69da12a34355745027c9db89877cdd8187df497171c2ee591bf7a80abd36187",
    },
    {
        "name": "status_transition_webhook",
        "payload": (
            '{"type":"status_transition","subscriptionUUID":"sub@01a0c5be-0000-7000-8000-00'
            '0000000001","data":{"previousStatus":"active","currentStatus":"low_on_funds","'
            'updatedAt":"2026-09-22T10:00:00Z"}}'
        ),
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": (
            '{"data":{"currentStatus":"low_on_funds","previousStatus":"active","updatedAt":'
            '"2026-09-22T10:00:00Z"},"subscriptionUUID":"sub@01a0c5be-0000-7000-8000-000000'
            '000001","type":"status_transition"}'
        ),
        "signature": "sha256=88708bfd796485695fd051a03a32ee3374ecf7b02ead27b1bbcf67504380f46a",
    },
]


# Second set of golden vectors generated by the Go SDK (scratch golden/vectors-new.json),
# kept verbatim: 19+-digit decimal strings, C0/C1 controls, lone surrogates, -0 and
# exponent forms, and key ordering by UTF-8 bytes (not UTF-16 code units).
GOLDEN_VECTORS_2 = [
    {
        "name": "decimal strings of 19+ digits stay strings",
        "payload": (
            '{"amountMinUnits":"1000000000000000000","txAmounts":{"minUnits":{"merchant":"9'
            '9000000000000000000","platform":"1000000000000000000000","referral":"0"}},"big'
            '":12345678901234567890,"id":"0001","neg":"-12345678901234567890"}'
        ),
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": (
            '{"amountMinUnits":"1000000000000000000","big":12345678901234567000,"id":"0001"'
            ',"neg":"-12345678901234567890","txAmounts":{"minUnits":{"merchant":"9900000000'
            '0000000000","platform":"1000000000000000000000","referral":"0"}}}'
        ),
        "signature": "sha256=88423199655b9f5e5db5e4b4fbdaea52d61f64f08837cad0a65bab1ea87b6a19",
    },
    {
        "name": "control characters",
        "payload": (
            '{"s":"a\\bb\\fc\\u0000d\\u001fe\\u007ff\\u0080g","k\\u0001":"x","tab":"\\t","c'
            'r":"\\r"}'
        ),
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": (
            '{"cr":"\\r","k\\u0001":"x","s":"a\\bb\\fc\\u0000d\\u001fe\x7ff\x80g","tab":"\\' 't"}'
        ),
        "signature": "sha256=4118c0a289dd2e4bb4ab62ad2b13a7e1ff60981717c75d6c1ce1c4848e82d5f0",
    },
    {
        "name": "lone surrogates become U+FFFD",
        "payload": '{"hi":"\\ud800x","lo":"\\udfff","pair":"\U0001f600"}',
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": '{"hi":"\ufffdx","lo":"\ufffd","pair":"\U0001f600"}',
        "signature": "sha256=b31ca0014545f32bf62e937955fe50e11c5a6cf68f57052008edd0cfb2af29d3",
    },
    {
        "name": "negative zero and exponent forms",
        "payload": '{"a":-0,"b":-0.0,"c":1E2,"d":1e-7,"e":-1.5e-10,"f":0.0,"g":-0.000001}',
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": '{"a":-0,"b":-0,"c":100,"d":1e-7,"e":-1.5e-10,"f":0,"g":-0.000001}',
        "signature": "sha256=45e3033a130332ab91bce58115d670ac83a9d4a41b59f51323c4e20625bcd2bc",
    },
    {
        "name": "keys are ordered by UTF-8 bytes",
        "payload": '{"\U0001f600":1,"\uffff":2,"a":3,"\xe9":4,"Z":5,"":6,"aa":7,"a\\u0000":8}',
        "secret": "whsec_golden_secret_0123456789",
        "timestamp": "1758540000",
        "canonical": '{"":6,"Z":5,"a":3,"a\\u0000":8,"aa":7,"\xe9":4,"\uffff":2,"\U0001f600":1}',
        "signature": "sha256=3b3885769c26eac4d862579cb4782135f5021d1ba5fa6c801d50f9228c164fb9",
    },
]


def now_ts() -> str:
    return str(int(time.time()))


class TestReferenceVectors:
    """Cross-SDK byte-for-byte agreement with the Go implementation."""

    @pytest.mark.parametrize("name,payload,canonical,_sig", REFERENCE_VECTORS)
    def test_canonical_form_matches_go(self, name, payload, canonical, _sig):
        assert canonical_json(payload) == canonical, f"canonical form drifted for {name}"

    @pytest.mark.parametrize("name,payload,_canonical,signature", REFERENCE_VECTORS)
    def test_signature_matches_go(self, name, payload, _canonical, signature):
        assert (
            compute_webhook_signature(SECRET, TIMESTAMP, payload) == signature
        ), f"signature drifted for {name}"


ALL_GOLDEN_VECTORS = GOLDEN_VECTORS + GOLDEN_VECTORS_2
GOLDEN_IDS = [v["name"] for v in ALL_GOLDEN_VECTORS]


class TestGoldenVectors:
    """The shared cross-SDK golden vectors: canonical form and signature, byte for byte."""

    @pytest.mark.parametrize("vector", ALL_GOLDEN_VECTORS, ids=GOLDEN_IDS)
    def test_canonical_form(self, vector):
        assert canonical_json(vector["payload"]) == vector["canonical"], vector["name"]

    @pytest.mark.parametrize("vector", ALL_GOLDEN_VECTORS, ids=GOLDEN_IDS)
    def test_canonical_form_from_bytes_and_decoded(self, vector):
        assert canonical_json(vector["payload"].encode("utf-8")) == vector["canonical"]
        if vector["name"] != "negative zero and exponent forms":
            # A payload pre-decoded by the stdlib parses "-0" as the integer 0 and loses the
            # sign, so that one vector is only byte-identical from the raw body.
            decoded = json.loads(vector["payload"])
            assert canonical_json(decoded) == vector["canonical"], vector["name"]

    @pytest.mark.parametrize("vector", ALL_GOLDEN_VECTORS, ids=GOLDEN_IDS)
    def test_signature(self, vector):
        computed = compute_webhook_signature(
            vector["secret"], vector["timestamp"], vector["payload"]
        )
        assert computed == vector["signature"], vector["name"]

    @pytest.mark.parametrize("vector", ALL_GOLDEN_VECTORS, ids=GOLDEN_IDS)
    def test_verifies_end_to_end(self, vector):
        verify_webhook_signature(
            vector["secret"],
            vector["timestamp"],
            vector["signature"],
            vector["payload"],
            skip_timestamp_check=True,
        )


class TestCanonicalJson:
    def test_sorts_keys_at_every_level(self):
        assert canonical_json('{"b":2,"a":1}') == '{"a":1,"b":2}'
        assert canonical_json('{"z":{"y":1,"x":2}}') == '{"z":{"x":2,"y":1}}'

    def test_preserves_array_order(self):
        # Arrays are ordered by definition: sorting them would change meaning.
        assert canonical_json('{"items":[3,1,2]}') == '{"items":[3,1,2]}'

    def test_drops_insignificant_whitespace(self):
        assert canonical_json('{\n  "a" : 1 }') == '{"a":1}'

    def test_accepts_bytes_str_and_decoded_objects(self):
        expected = '{"a":1,"b":2}'
        assert canonical_json('{"b":2,"a":1}') == expected
        assert canonical_json(b'{"b":2,"a":1}') == expected
        assert canonical_json({"b": 2, "a": 1}) == expected

    def test_whole_floats_render_as_integers_like_go(self):
        # Go decodes JSON numbers to float64 and re-encodes 1.0 as "1"; Python would keep
        # "1.0" and produce a different signature for an identical payload.
        assert canonical_json('{"a":1.0}') == '{"a":1}'
        assert canonical_json({"a": 1.0}) == '{"a":1}'

    def test_booleans_are_not_coerced_to_numbers(self):
        # bool is a subclass of int in Python: True must stay true, not become 1.
        assert canonical_json('{"a":true,"b":false}') == '{"a":true,"b":false}'

    def test_rejects_invalid_json_and_missing_payloads(self):
        with pytest.raises(ValidationError):
            canonical_json("{not json")
        with pytest.raises(ValidationError):
            canonical_json(None)


class TestVerifyWebhookSignature:
    payload = '{"uuid":"pay@abc","txType":"payment"}'

    def test_accepts_a_genuine_webhook(self):
        ts = now_ts()
        sig = compute_webhook_signature(SECRET, ts, self.payload)
        verify_webhook_signature(SECRET, ts, sig, self.payload)

    def test_accepts_a_payload_whose_keys_were_reordered(self):
        ts = now_ts()
        sig = compute_webhook_signature(SECRET, ts, '{"a":1,"b":2}')
        verify_webhook_signature(SECRET, ts, sig, '{"b":2,"a":1}')

    def test_rejects_a_tampered_payload(self):
        ts = now_ts()
        sig = compute_webhook_signature(SECRET, ts, self.payload)
        with pytest.raises(ValidationError, match="mismatch"):
            verify_webhook_signature(SECRET, ts, sig, '{"uuid":"pay@EVIL"}')

    def test_rejects_a_tampered_timestamp(self):
        ts = now_ts()
        sig = compute_webhook_signature(SECRET, ts, self.payload)
        with pytest.raises(ValidationError, match="mismatch"):
            verify_webhook_signature(SECRET, str(int(ts) - 30), sig, self.payload)

    def test_rejects_the_wrong_secret(self):
        ts = now_ts()
        sig = compute_webhook_signature(SECRET, ts, self.payload)
        with pytest.raises(ValidationError, match="mismatch"):
            verify_webhook_signature("whsec_wrong", ts, sig, self.payload)

    def test_rejects_a_replayed_webhook(self):
        old = str(int(time.time()) - 600)
        sig = compute_webhook_signature(SECRET, old, self.payload)
        with pytest.raises(ValidationError, match="expired"):
            verify_webhook_signature(SECRET, old, sig, self.payload)

    def test_rejects_a_future_timestamp(self):
        # Guards against a forged future timestamp extending the replay window.
        future = str(int(time.time()) + 600)
        sig = compute_webhook_signature(SECRET, future, self.payload)
        with pytest.raises(ValidationError, match="expired"):
            verify_webhook_signature(SECRET, future, sig, self.payload)

    def test_honours_a_custom_replay_window(self):
        old = str(int(time.time()) - 600)
        sig = compute_webhook_signature(SECRET, old, self.payload)
        verify_webhook_signature(SECRET, old, sig, self.payload, max_timestamp_age_seconds=1800)

    def test_rejects_a_non_numeric_timestamp(self):
        with pytest.raises(ValidationError):
            verify_webhook_signature(SECRET, "nope", "sha256=abc", self.payload)

    @pytest.mark.parametrize(
        "bad",
        [
            "1700000000\n",
            " 1700000000",
            "1700000000 ",
            "١٧٠٠٠٠٠٠٠٠",  # Arabic-Indic digits: Unicode \d, not ASCII
            "１７００",  # full-width digits
            "17e8",
            "0x10",
            "9223372036854775808",  # beyond int64, as Go's ParseInt rejects it
            "+-1",
        ],
    )
    def test_timestamp_parsing_matches_go_parse_int(self, bad):
        with pytest.raises(ValidationError, match="unix-seconds integer"):
            verify_webhook_signature(SECRET, bad, "sha256=abc", self.payload, now_seconds=0)

    def test_a_plus_signed_timestamp_is_accepted_like_go(self):
        ts = "+" + now_ts()
        sig = compute_webhook_signature(SECRET, ts, self.payload)
        verify_webhook_signature(SECRET, ts, sig, self.payload)

    @pytest.mark.parametrize("max_age", [0, -5])
    def test_a_non_positive_replay_window_means_the_default(self, max_age):
        now = 1_700_000_000
        recent = str(now - 200)  # inside the default 300 s window
        sig = compute_webhook_signature(SECRET, recent, self.payload)
        verify_webhook_signature(
            SECRET, recent, sig, self.payload, max_timestamp_age_seconds=max_age, now_seconds=now
        )

        stale = str(now - 400)
        sig = compute_webhook_signature(SECRET, stale, self.payload)
        with pytest.raises(ValidationError, match="expired"):
            verify_webhook_signature(
                SECRET, stale, sig, self.payload, max_timestamp_age_seconds=max_age, now_seconds=now
            )

    def test_extreme_timestamps_do_not_overflow(self):
        with pytest.raises(ValidationError, match="expired"):
            verify_webhook_signature(
                SECRET, "-9223372036854775808", "sha256=abc", self.payload, now_seconds=2**62
            )

    @pytest.mark.parametrize("bad", ["", "sha256=", "deadbeef", "sha512=abc"])
    def test_rejects_malformed_signatures(self, bad):
        with pytest.raises(ValidationError):
            verify_webhook_signature(SECRET, now_ts(), bad, self.payload)


class TestCanonicalEdgeCases:
    def test_lone_surrogates_become_replacement_characters(self):
        assert canonical_json('{"s":"\\ud800x"}') == '{"s":"\ufffdx"}'
        assert canonical_json({"k\udfff": "\ud800"}) == '{"k\ufffd":"\ufffd"}'
        # A signature can be computed (the canonical form encodes as UTF-8).
        assert compute_webhook_signature(SECRET, TIMESTAMP, '{"s":"\\ud800"}').startswith("sha256=")

    def test_keys_colliding_after_replacement_keep_the_last_value_like_go(self):
        assert canonical_json('{"\\ud800":1,"\\udbff":2}') == '{"\ufffd":2}'

    def test_non_finite_numbers_are_rejected(self):
        for payload in ('{"a":NaN}', '{"a":Infinity}', '{"a":1e400}', {"a": float("nan")}):
            with pytest.raises(ValidationError):
                canonical_json(payload)


class TestParseWebhooks:
    def test_parses_a_transaction_webhook(self):
        vector = next(v for v in GOLDEN_VECTORS if v["name"] == "transaction_webhook")
        event = parse_session_webhook(vector["payload"])

        assert isinstance(event, SessionWebhookResponse)
        assert isinstance(event.session, OneTimePaymentSession)
        assert event.session.organization_id == 7 and event.session.fee_bps == 100
        assert event.status is not None and event.status.status == "completed"
        assert event.status.settlement_details is not None
        assert event.status.settlement_details.tx_metadata.main_currency_price_usd == 0.00001234
        assert event.session.available_currencies == [1, 2, 3]

    def test_parses_a_subscription_session_webhook(self):
        body = {
            "uuid": "sub@1",
            "txType": "createSubscription",
            "status": {"status": "completed"},
            "session": {"uuid": "sub@1", "txType": "createSubscription", "frequency": 60},
        }
        event = parse_session_webhook(json.dumps(body).encode())

        assert isinstance(event.session, SubscriptionSession) and event.session.frequency == 60
        assert event.management_page_link == ""

    def test_parses_billing_and_transition_webhooks(self):
        billing = next(v for v in GOLDEN_VECTORS if v["name"] == "subscription_billing_webhook")
        event = parse_subscription_webhook(billing["payload"])
        assert event.type == SubscriptionWebhookType.BILLING
        assert isinstance(event.data, SubscriptionHistory)
        assert event.data.metadata.fee_bps == 100 and event.data.product_id == 9

        transition = next(v for v in GOLDEN_VECTORS if v["name"] == "status_transition_webhook")
        event = parse_subscription_webhook(json.loads(transition["payload"]))
        assert event.data.current_status == SubscriptionStatus.LOW_ON_FUNDS
        assert event.subscription_reference == ""

    @pytest.mark.parametrize(
        "body", [b"not json", "[1,2]", '{"uuid": 5}', '{"session": "x"}', None, '{"a":NaN}']
    )
    def test_invalid_session_webhooks_raise_the_sdk_validation_error(self, body):
        with pytest.raises(ValidationError):
            parse_session_webhook(body)

    @pytest.mark.parametrize(
        "body", [b"{", '{"type": 1}', '{"type":"billing","data":{"amount":"x"}}']
    )
    def test_invalid_subscription_webhooks_raise_the_sdk_validation_error(self, body):
        with pytest.raises(ValidationError):
            parse_subscription_webhook(body)


class TestExtractWebhookHeaders:
    def test_reads_headers_case_insensitively(self):
        h = extract_webhook_headers(
            {
                "x-webhook-signature-256": "sha256=abc",
                "X-Webhook-Timestamp": "1700000000",
                "x-webhook-id": "pay@abc",
            }
        )
        assert h["signature"] == "sha256=abc"
        assert h["timestamp"] == "1700000000"
        assert h["webhook_id"] == "pay@abc"
        assert h["is_test"] is False

    def test_flags_the_dashboard_test_webhook(self):
        h = extract_webhook_headers({"X-Webhook-Id": TEST_WEBHOOK_ID})
        assert h["is_test"] is True

    def test_takes_the_first_value_of_a_repeated_header(self):
        h = extract_webhook_headers({"x-webhook-timestamp": ["1700000000", "1700000001"]})
        assert h["timestamp"] == "1700000000"

    def test_missing_headers_yield_empty_strings(self):
        h = extract_webhook_headers({})
        assert h["signature"] == ""
        assert h["timestamp"] == ""
        assert h["is_test"] is False


class TestOptionalFieldsEmptyString:
    """An empty optional field means "not provided", matching the API's omitempty."""

    def test_empty_strings_are_treated_as_absent(self):
        from qbitflow.dto.transaction.session import CreatePaymentSessionDto

        # Must not raise: os.environ.get("SUCCESS_URL", "") is a normal pattern.
        CreatePaymentSessionDto(product_id=339, success_url="", product_name="", description="")

    def test_a_non_empty_bad_value_is_still_rejected(self):
        from qbitflow.dto.transaction.session import CreatePaymentSessionDto

        with pytest.raises(ValidationError, match="success_url"):
            CreatePaymentSessionDto(product_id=339, success_url="javascript:alert(1)")
